import random #Import the random library.

guess_number = random.randint(1, 10)#Specify the Randint function.
#print random number generated by Randint function.
print(guess_number)
#Specify the user guess number.
user_guess = input("Guess a number between 1 and 10: ")
#specify the user guess input into int variable.
user_guess = int(user_guess)
#write the condition  for userguess and guess number.

if user_guess == guess_number:
    #print for guessing correct number.
    print("Congratulations! You guessed the right number.")
    #print for wrong guess number.
else:
    print("Sorry, your guess doesn't match.")



